### ISSUE TITLE
kde store

### ISSUE THREAD

**Issue by steverweber** [tsoernes/kwin-quick-tile-2#1]
I think others would also find this script helpful.

perhaps add it to: https://store.kde.org
so it's ease to install and kde developers might take the hint to make something like this the default.

**Comment by steverweber** [comment]
seems like the latest kde now includes improved default shortcut keys for window managment,
so perhaps this script is not needed in the store.

**Comment by tsoernes** [comment]
The script has been published: https://www.opendesktop.org/p/1259484/
