### ISSUE TITLE
Plasma 5.22: Tiling no longer works over all screens

### ISSUE THREAD

**Issue by aksdb** [tsoernes/kwin-quick-tile-2#4]
Quick Tile 2 worked perfectly until Plasma 5.22. I have two screens (the right one being my main monitor). When I try to tile anything to the right side of the right screen, it snaps to the right side of the left screen. If I press the button again, it snaps to the left side of the right screen, again to the right of the left screen, and so on. I can no longer uses hotkeys to move windows to the right side of my right screen.

Tiling a window via drag & drop still works, so I assume some coordinates are reported differently within the kwin script.

**Comment by tim-hilt** [comment]
Hmm... This might have something to do with a new KWin-version, but I see more malfunction there: Tiling doesn't seem to work equally good on all monitors. Especially if you have a configuration, that has different size screens. Here is a gif of what it looks like, when I try to tile a window on my 4k monitor + 1080p laptop:
![Peek 2022-02-08 09-07](https://user-images.githubusercontent.com/16037579/152944781-bb710997-99b6-48b2-bd19-e206bb5c4f8b.gif)
Also, tiling always only works on the screen the window was launched on. Do you still use the script and experience a similar behavior? If so, do you have a clue where this might come from?
